name: backend
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  dart_frog: ^1.0.1

dev_dependencies:
  demo_analysis:
    path: ../packages/demo_analysis
  mocktail: ^0.3.0
  test: ^1.24.1
  very_good_analysis: ^4.0.0+1
