name: app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  custom_info_window: ^1.0.1
  demo_data_models:
    path: ../../packages/demo_data_models
  demo_errors:
    path: ../../packages/demo_errors
  demo_repositories:
    path: ../../packages/demo_repositories
  demo_riverpod_providers:
    path: ../../packages/demo_riverpod_providers
  demo_theme:
    path: ../../packages/demo_theme
  demo_ui:
    path: ../../packages/demo_ui
  easy_debounce: ^2.0.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  go_router: ^6.5.5
  google_maps_flutter: ^2.2.5
  hooks_riverpod: ^2.3.4
  riverpod_annotation: ^2.1.1

dev_dependencies:
  build_runner: ^2.3.3
  dart_code_metrics: ^5.7.0
  demo_analysis:
    path: ../../packages/demo_analysis
  dependency_validator: ^3.2.2
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  very_good_analysis: ^4.0.0+1
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.1.6

flutter:
  uses-material-design: true
